---
- name: "Installing basics"
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
  - tree
  - unzip
  - jq
  - htop
  - curl
  - wget
  - git
  - telnet
  - vim
  - awscli
  - cloud-init