---

- name: "Installing docker"
  package:
    name: docker
    state: latest
  become: true

- name: "Adding docker group"
  group:
    name: docker
    state: present

- name: "Registering docker"
  service:
    name: "docker"
    enabled: true
  become: true

- name: "Add ECR auto login script"
  copy:
    src: ecr-auto-login
    dest: /usr/bin/
    owner: root
    group: root
    mode: 0755

- name: "Add ECR auto login services"
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
    owner: root
    group: root
    mode: 0644
  with_items:
    - ecr.timer
    - ecr.service

- name: "Enable ECR services"
  service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - ecr.timer
    - ecr.service

- name: "Install docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: with_compose
  become: true

- name: "Add dnsmasq config"
  copy:
    src: "dnsmasq-docker"
    dest: "/etc/dnsmasq.d/20-docker"
