consul_version: 1.0.0
consul_zip_archive: "consul_{{ consul_version }}_linux_amd64.zip"
consul_download_path: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_zip_archive }}"
consul_download_checksum: "sha256:585782e1fb25a2096e1776e2da206866b1d9e1f10b71317e682e03125f22f479"
consul_download_directory: "/tmp"
consul_config_dir: "/etc/consul/conf.d"
consul_data_dir: "/var/local/consul"
consul_home_dir: "/var/local/consul"
consul_log_file: "/var/log/consul.log"
consul_server: false
nosce_dir: /etc/nosce